### ISSUE TITLE
Visual bug starting in patch 6.2

### ISSUE THREAD

**Issue by rd184** [xupwup/LoLPatcher#12]
The news are not shown anymore and the status bar is showing in the upper part now. This started since patch 6.2 released earlier today.

![image](https://cloud.githubusercontent.com/assets/8683399/12650712/d2ca2bd8-c5b1-11e5-9544-72896b61648b.png)

**Comment by rd184** [comment]
It got back to normal now. Closing issue.

**Comment by rd184** [comment]
Reopening it. It seems to be an issue with Riot, however, a "fallback" in case this happens would help.

**Comment by xupwup** [comment]
I replaced the whole news module. The news it showed was mostly out of date, and I don't really feel like properly updating it. I replaced it by a flow simulation. See https://github.com/xupwup/LoLPatcher/commit/0262203a3bf78a901578b4af3528d5f763c15671
