### ISSUE TITLE
Files are always saved in the home directory with OpenJDK in Linux

### ISSUE THREAD

**Issue by izrol3** [xupwup/LoLPatcher#15]
When I run the program with OpenJDK, the files downloaded are not saved in the directory containing the program. Instead, the files are saved in the home directory.
For your information, the operating system of my computer is Lubuntu 14.04.
Thanks in advance.

**Comment by xupwup** [comment]
The program simply dumps the files in the working directory. The easiest way to get it working is to make a file called "run.sh", and put the following text inside:

```
#!/bin/sh
java -jar SelfPatchFinalizer.jar LoLPatcher.jar
```

Running that should ensure the current directory is set correctly. (maybe you need to do `chmod +x run.sh`)
