### ISSUE TITLE
Archive purging

### ISSUE THREAD

**Issue by skvatboy** [xupwup/LoLPatcher#18]
When I run the Archive purging

`java.io.IOException: Invalid installation. Expected one archive, found 2 in /wineprefix/LeagueOfLegends/drive_c/Riot Games/League of Legends/RADS/projects/lol_game_client/filearchives/0.0.1.2.
    at lolpatcher.ArchivePurgeTask.purgeArchive(ArchivePurgeTask.java:88)
    at lolpatcher.ArchivePurgeTask.patch(ArchivePurgeTask.java:65)
    at lolpatcher.PatchTask.run(PatchTask.java:38)
`
OpenJDK
Ubuntu 14.04

**Comment by xupwup** [comment]
RADS/projects/lol_game_client/filearchives/0.0.1.2 should only contain one .raf file, and one .raf.dat file (they form a pair). There should only be one pair in that directory, you appear to have more than one. You can safely delete anything in that directory, running quick repair will fix it.

**Comment by skvatboy** [comment]
Thanks for your help.
