### ISSUE TITLE
Patcher down?

### ISSUE THREAD

**Issue by faceuckadoss** [xupwup/LoLPatcher#20]
I´ve been trying to enter lolpatcher.xupwup.nl/ and it doesnt seem to deliver any packages, sounds like the website is down, also I cant play anymore with your patcher cause its just still at 2/2 and doesnt seem to download or upload anything from the Resource Monitor on Network, perhaps something´s wrong with the patcher? or is it just me...
Anyway, thanks for reading, looking forward for an answer

**Comment by xupwup** [comment]
It seems to work fine right now... This site is useful by the way: http://www.downforeveryoneorjustme.com/

**Comment by faceuckadoss** [comment]
Sorry, there seems to be some kind of problem with my network service, contacting them right away.
Thanks for the fast answer xupwup.
