### ISSUE TITLE
No download

### ISSUE THREAD

**Issue by chroteus** [xupwup/LoLPatcher#4]
What the title says. It just says 0KiB/s while remaining minutes increase.

**Comment by xupwup** [comment]
That probably means your internet connection is failing.

**Comment by chroteus** [comment]
No, not really.
I've noticed something though: Even though patcher says it does not download the new version, LoLPatcher.jar is growing in size until it reaches 4,445KB in size and then it stops growing. Patcher still says "0KiB/s". Changing file extension of .new patcher to .jar does not help it, as it doesn't work.

**Comment by xupwup** [comment]
Try downloading http://lolpatcher.xupwup.nl/data/LoLPatcher.jar manually.

**Comment by chroteus** [comment]
Ah yes, it downloaded nicely. Thanks for your help.
