### ISSUE TITLE
Patcher is looking for RiotRadsIO.dll in the wrong directory

### ISSUE THREAD

**Issue by fwinest-JediThug** [xupwup/LoLPatcher#7]
I get this error near the end of the update process:
```
java.io.FileNotFoundException: RADS/projects/lol_patcher/releases/0.0.0.45/deploy/RiotRadsIO.dll (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at lolpatcher.CopyTask.copy(CopyTask.java:49)
	at lolpatcher.CopyTask.patch(CopyTask.java:72)
	at lolpatcher.PatchTask.run(PatchTask.java:38)
```
I fixed this for myself by copying RiotRadsIO.dll from the RADS directory to that specific location, but that might not be desirable.

**Comment by xupwup** [comment]
The patcher used to download RiotRadsIO.dll through riot's lol_patcher project, but apparently they stopped releasing it that way. Luckily RiotRadsIO.dll is no longer needed, so i should remove the whole task. That means your change is a fine workaround (an empty text file called "RiotRadsIO.dll" might even work). I'll properly fix the problem sometime next week.
